/**
 * Gestione icone Heroicons (outline 24×24) per il pacchetto npm.
 *
 * - `sync` — da `@iconify-json/heroicons`: rigenera `public/tailwind-icons/*.svg` e `models/icons.ts`.
 *   Va eseguito **prima** di `ng build` (serve il TS compilabile).
 * - `dist` — dopo la build: copia `public/tailwind-icons/*.svg` in `dist/.../tailwind-icons`.
 *
 * Licenza icone: MIT — Heroicons (Tailwind Labs).
 * https://heroicons.com/
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const iconsJsonPath = path.join(root, 'node_modules', '@iconify-json', 'heroicons', 'icons.json');
const publicDir = path.join(root, 'public', 'tailwind-icons');
const iconsTsPath = path.join(
  root,
  'projects',
  'angular-tailwind-components',
  'src',
  'lib',
  'models',
  'icons.ts'
);
const destDir = path.join(root, 'dist', 'angular-tailwind-components', 'tailwind-icons');

function isHeroiconsOutlineKey(key) {
  return (
    !key.endsWith('-solid') && !key.endsWith('-16-solid') && !key.endsWith('-20-solid')
  );
}

function syncFromIconify() {
  if (!fs.existsSync(iconsJsonPath)) {
    console.error('Missing:', iconsJsonPath, '(run npm install)');
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(iconsJsonPath, 'utf8'));
  const defaultW = data.width || 24;
  const defaultH = data.height || 24;

  const entries = [];
  for (const key of Object.keys(data.icons || {})) {
    if (!isHeroiconsOutlineKey(key)) continue;
    const slug = key;
    const icon = data.icons[key];
    const body = icon && icon.body;
    if (!body) {
      console.warn('skip no body:', key);
      continue;
    }
    const w = icon.width ?? defaultW;
    const h = icon.height ?? defaultH;
    entries.push({ key, slug, body, w, h });
  }

  const bySlug = new Map();
  for (const e of entries) {
    const prev = bySlug.get(e.slug);
    if (prev) {
      throw new Error(`Duplicate slug "${e.slug}" from keys "${prev.key}" and "${e.key}"`);
    }
    bySlug.set(e.slug, e);
  }

  fs.mkdirSync(publicDir, { recursive: true });
  for (const f of fs.readdirSync(publicDir)) {
    if (f.endsWith('.svg')) {
      fs.unlinkSync(path.join(publicDir, f));
    }
  }

  for (const { slug, body, w, h } of entries) {
    const svg =
      `<?xml version="1.0" encoding="UTF-8"?>\n` +
      `<!-- Heroicons (MIT) — https://heroicons.com/ -->\n` +
      `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet">\n` +
      `${body}\n` +
      `</svg>\n`;
    fs.writeFileSync(path.join(publicDir, `${slug}.svg`), svg, 'utf8');
  }

  entries.sort((a, b) => a.slug.localeCompare(b.slug));
  const lines = entries.map((e) => `  '${e.slug}'`).join(',\n');

  const ts =
    `/**\n` +
    ` * Heroicons outline icon names (kebab-case). SVG assets in \`public/tailwind-icons/\`.\n` +
    ` * Generated by scripts/copy-icons.js sync — do not edit manually.\n` +
    ` *\n` +
    ` * Icons: Heroicons (Tailwind Labs), MIT — https://heroicons.com/\n` +
    ` */\n` +
    `export const TAILWIND_HEROICON_NAMES = [\n${lines},\n] as const;\n\n` +
    `/** Use names listed in {@link TAILWIND_HEROICON_NAMES} (compile-time union omitted — large sets break Angular template inference). */\n` +
    `export type TailwindHeroicon = string;\n`;

  fs.writeFileSync(iconsTsPath, ts, 'utf8');

  console.log(`copy-icons sync: wrote ${entries.length} SVG(s) → ${publicDir}`);
  console.log(`copy-icons sync: wrote ${iconsTsPath}`);
}

function copyToDist() {
  if (!fs.existsSync(publicDir)) {
    console.error('Missing directory:', publicDir);
    process.exit(1);
  }

  fs.mkdirSync(destDir, { recursive: true });
  let n = 0;
  for (const name of fs.readdirSync(publicDir)) {
    if (!name.endsWith('.svg')) continue;
    fs.copyFileSync(path.join(publicDir, name), path.join(destDir, name));
    n++;
  }
  console.log(`copy-icons dist: copied ${n} SVG(s) → dist/angular-tailwind-components/tailwind-icons`);
}

const cmd = process.argv[2];
if (cmd === 'sync') {
  syncFromIconify();
} else if (cmd === 'dist') {
  copyToDist();
} else {
  console.error('Usage: node scripts/copy-icons.js <sync|dist>');
  console.error('  sync  Regenerate SVG + icons.ts from @iconify-json/heroicons (run before ng build)');
  console.error('  dist  Copy public/tailwind-icons → dist/.../tailwind-icons (run after ng build)');
  process.exit(1);
}
